# @package _global_

# specify here default evaluation configuration
defaults:
  - _self_
  - datamodule: bert.yaml # choose the datamodule for evaluation
  - model: bert.yaml
  - callbacks: null
  - metrics: many_metrics.yaml
  - logger: null
  - trainer: default.yaml
  - log_dir: evaluation.yaml
  - experiment: null

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

original_work_dir: ${hydra:runtime.cwd}

data_dir: ${original_work_dir}/data/

print_config: True

ignore_warnings: True

seed: 3435

name: "default"

# passing checkpoint path is necessary
ckpt_path: ${original_work_dir}/logs/ckpts/best.ckpt
